sudo: required

services:
    - docker

before_install:
    - docker build -t ahmedou/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run ahmedou/react-test npm test -- --coverage

after_success:
    - docker build -t ahmedouyahya/client ./client
    - docker build -t ahmedouyahya/nginx ./nginx
    - docker build -t ahmedouyahya/server ./server
    - docker build -t ahmedouyahya/worker ./worker
  
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin


    # THIS IS A COMMENT
    - docker push ahmedouyahya/client
    - docker push ahmedouyahya/nginx
    - docker push ahmedouyahya/server
    - docker push ahmedouyahya/worker