sudo: required

services:
    - docker

before_install:
    - docker build -t ahmedou/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run ahmedou/react-test npm test -- --coverage

after_success:
    - docker build -t ahmedou/client ./client
    - docker build -t ahmedou/nginx ./nginx
    - docker build -t ahmedou/server ./server
    - docker build -t ahmedou/worker ./worker
  
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin


    # THIS IS A COMMENT
    - docker push ahmedou/client
    - docker push ahmedou/nginx
    - docker push ahmedou/server
    - docker push ahmedou/worker